spring:
  application:
    name: limitmodule
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/limit_db
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    generate-ddl: false
