spring:
  application:
    name: limitmodule
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/limit_db
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    generate-ddl: false

integrations:
  payments:
    client:
      rest-template-properties:
        url: "http://localhost:8031"
        connect_timeout: 1s
        read_timeout: 5s

limits:
  properties:
    limit: 10000.00
