version: "3.1"

services:
  wiremock:
    image: "rodolpheche/wiremock"
    container_name: wiremock
    ports:
      - "8031:8080"
    volumes:
      - ./wiremock/__files:/home/wiremock/__files
      - ./wiremock/mappings:/home/wiremock/mappings
    command:
      - -verbose
      - -global-response-templating